---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - php
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.php"
exclude_paths: []
